--- 

# $ ansible-playbook -i inventory.txt create_gcp_instance.yml -t create-instances
# $ ansible-playbook -i inventory.txt create_gcp_instance.yml -t delete-instances

- hosts: nodes
  gather_facts: no
  connection: local
  vars:
    gcp_machine_type: 'e2-small'
    gcp_image: 'projects/gce-uefi-images/global/images/centos-7-v20200403'
    gcp_project: 'ehf-95020' 
    gcp_zone: 'us-west1-b'
    gcp_network: 'default'
    gcp_sa_file: 'ehf-95020.json'
    gcp_sa_email: "{{ (lookup('file', '{{ gcp_sa_file }}') | from_json).get('client_email') }}"
    ansible_python_interpreter: /opt/homebrew/bin/python3
  tasks:
    - name: "create instance"
      gcp_compute_instance:
        name: "test-dev-instance-{{ item }}"
        machine_type: "{{ gcp_machine_type }}"
        disks:
        - auto_delete: 'true'
          boot: 'true'
          initialize_params:
            disk_size_gb: 20
            source_image: "{{ gcp_image }}"
        labels:
          env: dev
          app: web 
        network_interfaces:
        - access_configs:
          - name: "External NAT"
            type: "ONE_TO_ONE_NAT"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ gcp_sa_file }}"
        service_accounts:
        - email: "{{ gcp_sa_email }}"
          scopes:
          - https://www.googleapis.com/auth/cloud-platform
        state: present
      loop: "{{ range(1,5) }}"
      tags:
        - create-instances
   
    - name: "delete instance"
      gcp_compute_instance:
        name: "test-dev-instance-{{ item }}"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ gcp_sa_file }}"
        state: absent
      loop: "{{ range(1,5) }}"
      tags:
        - delete-instances
        
        
