--- 

# $ export GCP_OS_MGMT_CONF=$HOME/Workspace/conf/my-conf.json
# $ ansible-playbook -i inventory.txt create_gcp_instance.yml -t create-instances
# $ ansible-playbook -i inventory.txt create_gcp_instance.yml -t delete-instances

- hosts: nodes
  gather_facts: no
  connection: local
  vars:
    conf_file: "{{ lookup('env','GCP_OS_MGMT_CONF') }}"
    gcp_sa_file: "{{ (lookup('file', '{{ conf_file }}') | from_json).get('gcp_sa_file') }}"
    gcp_machine_type: "{{ (lookup('file', '{{ conf_file }}') | from_json).get('gcp_machine_type') }}"
    gcp_image: "{{ (lookup('file', '{{ conf_file }}') | from_json).get('gcp_image_full') }}"
    gcp_zone: "{{ (lookup('file', '{{ conf_file }}') | from_json).get('gcp_zone') }}"
    gcp_network: "{{ (lookup('file', '{{ conf_file }}') | from_json).get('gcp_network') }}"
    gcp_project: "{{ (lookup('file', '{{ gcp_sa_file }}') | from_json).get('project_id') }}"
    gcp_sa_email: "{{ (lookup('file', '{{ gcp_sa_file }}') | from_json).get('client_email') }}"
    gcp_api_auth_scope: 'https://www.googleapis.com/auth/cloud-platform'
    ansible_python_interpreter: "{{ (lookup('file', '{{ conf_file }}') | from_json).get('python_interpreter') }}"
  tasks:
    - name: "create instance"
      gcp_compute_instance:
        name: "test-dev-instance-{{ item }}"
        machine_type: "{{ gcp_machine_type }}"
        disks:
        - auto_delete: 'true'
          boot: 'true'
          initialize_params:
            disk_size_gb: 20
            source_image: "{{ gcp_image }}"
        labels:
          env: dev
          app: web 
        network_interfaces:
        - access_configs:
          - name: "External NAT"
            type: "ONE_TO_ONE_NAT"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ gcp_sa_file }}"
        service_accounts:
        - email: "{{ gcp_sa_email }}"
          scopes:
          - "{{ gcp_api_auth_scope }}"
        state: present
      loop: "{{ range(1,5) }}"
      tags:
        - create-instances
   
    - name: "delete instance"
      gcp_compute_instance:
        name: "test-dev-instance-{{ item }}"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ gcp_sa_file }}"
        state: absent
      loop: "{{ range(1,5) }}"
      tags:
        - delete-instances
        
        
